### ISSUE TITLE
Make design more responsive

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan#10]
Cater for typical desktop, mobile and perhaps tablet-sized screens. Portrait and non-portrait?

- [x] sidebar width
- [x] the sidebar ("bottombar") mini version currently just disappears on mobile #16
- [x] widths/heights of popups, dialogs, snackbar etc
- [ ] …

**Comment by rotsee** [comment]
Added a menu button to show the “bottombar” on small screens

**Comment by quite** [comment]
@rotsee yes! det workaround för den där buggen

**Comment by rotsee** [comment]
“Good enough”
