### ISSUE TITLE
Should we allow any formatting in the tree descriptions

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan#14]
Also, there is currently some HTML in there. I suggests that we at least don't allow HTML, and for the final database transfer we'd strip that.

**Comment by rotsee** [comment]
Agreed!

Checklist:

- [ ] 1. Update Python data transfer script to strip HTML
- [ ] 2. Make the API strip html tags
- - - 
- [ ] 3. Add a preview endpoint to the API, that just returns the results of that cleanup
- [ ] 4. Run preview content through the preview endpoint

(3 and 4 could wait until after the first release)
