### ISSUE TITLE
Should we allow only predefined tree types?

### ISSUE THREAD

**Issue by rotsee** [fruktkartan/fruktkartan#15]
Should we define a set of allowed tree types, or allow any reasonable text string? Experience from Fruktkartan 1 is that:

 - on one hand there is some “ontology creep” when allowing anything (like people replacing “apple” with the name of a specific apple variety). Some oversight and editing will be needed.
 - on the other hand useful things we didn't think of sometimes turn up (like that time when someone opened up their small pineapple garden to the public)

**Comment by quite** [comment]
Tricky one :-)

Let's say we only allow predefined types, then it sounds like we would need a smooth way to request new types -- with somebody responding etc?

And as you say, allowing anything also might result in a need for maintenance...

**Comment by quite** [comment]
I'm thinking that for a launch, we'll stay with allowing only predefined types.
