### ISSUE TITLE
Mobile / small screen "sidebar"

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan#16]
How do we want it to work?

Currently the sidebar is displayed at the bottom, and the "hide panel" button is not displayed. Due to `<v-list class="d-none d-lg-block">` -- "don't display, except if viewport >= *large* and type is block", right.

- Do we want this mobile sidebar to go away almost completely? With some tiny tap:able bar at the bottom?

- Or do we want it do be folded into the left edge to become a mini variant? This actually almost works if we bring back the "hide panel" button. *Except* that it is not really *mini*:

![a](https://user-images.githubusercontent.com/488679/74512002-93b99580-4f07-11ea-9a51-9c18c5058de8.png)

In this case tapping on the map should also hide the panel in the same way.

- Or something different?

**Comment by rotsee** [comment]
Maybe the first option then, with something tap-able to bring up the menu?

![image](https://user-images.githubusercontent.com/122874/74682550-a44b6380-51c6-11ea-8efc-6e3524e5fbd8.png)

**Comment by quite** [comment]
Yes, something like that! Maybe it'll have to be something custom, instead of a lot of tweaks to our current larger-screen navigation-drawer with minivariant.

**Comment by rotsee** [comment]
Added something that works (though not pretty). Closing this, and using more specific issues for further todo's
