### ISSUE TITLE
Image not showing on preview

### ISSUE THREAD

**Issue by rotsee** [fruktkartan/fruktkartan#24]
The preview when adding a new tree (or updating an existing tree) does not show the image. This is because the image is not yet processed at AWS lambda. Possible workarounds:

1. Make the upload bucket at s3 public, and show the image from there
2. Use the same preview technique as we do in the tree editor, in case a new file has been uploaded

**Comment by rotsee** [comment]
Added a message about the image still being processed, until we have a better fix

**Comment by quite** [comment]
I actually see the image in the preview. Saw the message once I think, but haven't played so much with it.

**Comment by rotsee** [comment]
Yeah, it depends on if the resize script had time to finish before your browser tried to load the image. You can trigger it by uploading a ridiculously big image, and then _quickly_ pressing “continue”... :)

**Comment by quite** [comment]
This warning message doesn't seem to ever go away, if displayed once. And it show up on all trees.
Uploading an image that doesn't provoke the warning does make it go away.

**Comment by rotsee** [comment]
> This warning message doesn't seem to ever go away, if displayed once. And it show up on all trees.
> Uploading an image that doesn't provoke the warning does make it go away.

I'm not able to reproduce this. What are the exact steps needed for this to happen?

**Comment by quite** [comment]
It's somehow not hard to reproduce for me. I also easily get the warning now...

- Add a new tree. I add the image last, so I quickly can click Publish and provoke the warning :)
- Click some other tree to view it, and the warning is there
- Click newly added tree; still warns
- Add new tree #2; warning still around
- Delete #2, with no image
- Warning gone

**Comment by rotsee** [comment]
Weird, doesn't seem to happen for me...

**Comment by quite** [comment]
Ok, it only seems to happen with this Android webview-based (so chromium-based) browser "Privacy". Let's ignore that one for now :) Can't reproduce in FF on desktop, Chrome in Android, ..
