### ISSUE TITLE
Reset type/desc/file when cancelling ("avbryt") both AddTree and Preview

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan#26]
So that the user can start anew, like after submitting. Maybe?

**Comment by rotsee** [comment]
After submitting, the form _is_ reset (if not, that's a bug!), but not after cancelling. My thought was that if you accidentally cancel editing, you should not have to start anew. But I can also see how someone would use ‘cancel’ as a way to start over from scratch, so I'm not sure what the right approach is...

**Comment by quite** [comment]
Yes yes, submitting resets.

I'm fine with leaving it as is, too. You had a thought behind it :)
