### ISSUE TITLE
Action buttons don't fit small screens

### ISSUE THREAD

**Issue by rotsee** [fruktkartan/fruktkartan#29]
![Screenshot_20200523_225920_com android chrome](https://user-images.githubusercontent.com/122874/82740485-76d40000-9d49-11ea-96c4-d26927e047ad.jpg)

We could stack them, or make them smaller?

**Comment by quite** [comment]
That's not even small?! High resolution! Looks like you have to shrink the padding and maybe also decrease the font-size slightly, to fit in even smaller screens. Adding `small` to the `v-btn` seems to do that, but is it enough... There is also the add tree dialog, and more?

**Comment by quite** [comment]
What about moving Remove-button to the Edit-page? I was thinking that it is slightly too easy to delete trees.

**Comment by quite** [comment]
It works well! 

I was thinking before to remove the uppercasing in buttons. Against materialdesign sure, but I think buttons are obvious enough, and it's hard on the eyes. This would make them narrower as well. I'll make the Ta bort button a bit smaller as well.

**Comment by quite** [comment]
![localhost_8080_(Nexus 4)](https://user-images.githubusercontent.com/488679/82758664-2b246380-9de8-11ea-8f0c-f02874b711e5.png)
