### ISSUE TITLE
Implement remove trees

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan#3]

**Comment by rotsee** [comment]
Untested, but should work: https://github.com/fruktkartan/fruktkartan/blob/master/src/components/Map.vue#L224

**Comment by quite** [comment]
Old fruktkartan is backed by the wiki, so changes are kept. If I've understood the api, deletes are marked with IP of who deleted it. That's good. I like not requiring login!

And edits, once implemented in the frontend, will always create a new tree?  `const key = murmurhash.v3("" + req.params.lat + req.params.lon, Date.now())`
