### ISSUE TITLE
"F" logo is not displayed in the minivariant of the drawer

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan#31]
Did it disappear by mistake? Code is still there...

**Comment by rotsee** [comment]
What browser? I can still see it in Firefox and Chrome...

**Comment by quite** [comment]
In both of them. The drawer at the bottom has the decription-filtering at the top. :thinking:

**Comment by quite** [comment]
Argh! I meant the mobile-break-point view, not minivariant. And it is `d-none` that hides it in mobile layout.

**Comment by rotsee** [comment]
Reopening this; Maybe we _do_ want to display a logo on mobile, not that there are fewer items on the menu? What do you think? 

![image](https://user-images.githubusercontent.com/122874/82868846-9deb2700-9f2d-11ea-8f91-82c4557dccef.png)

Maybe if we make it a bit smaller?

**Comment by quite** [comment]
Yes, I would be good to have it there. But smaller yes!
