### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan#32]
I'd like to set a license on the code, and also the data. The latter maybe visible when adding tree?

I'm not sure as which.

**Comment by quite** [comment]
Proposing AGPL3 for all code, since it's a website.

**Comment by rotsee** [comment]
You read my mind, was just logging in to add this... :)

For the code I have no opinions, AGPL3 is fine with me.

As for the data, users adding trees to the former site agreed on putting their contributions under the [''Open database license'' (ODbL)](https://opendatacommons.org/licenses/odbl/summary/), so if we keep that, we have backwards compatibility. One issue with ODbL is that it's not very well suited for images. Maybe we should add that images will be available under a CC license?
CC-0?

**Comment by quite** [comment]
Code is AGPLv3:d now.

Totally makes sense to use the same license yup. And, ah, that's OSM's license now, wasn't aware :)   Yes, CC0 sounds good if ODbL isn't suited! yup

**Comment by quite** [comment]
https://github.com/fruktkartan/fruktkartan/tree/license-data
