### ISSUE TITLE
mobile nav drawer has lots of space at the bottom

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan#33]
![fruktkartan se_](https://user-images.githubusercontent.com/488679/83334473-198b0200-a2a7-11ea-8be3-1b4b5861d27e.png)

**Comment by rotsee** [comment]
Fixed with an css override, as the NavigationDrawer component had no option for adjusting the height.
https://github.com/fruktkartan/fruktkartan/commit/2dd8d8b521d19fb4c06e6956923ba64a92d58cfd
