### ISSUE TITLE
Add 404 page

### ISSUE THREAD

**Issue by rotsee** [fruktkartan/fruktkartan#44]

**Comment by quite** [comment]
We're good then? Or should there be something for https://fruktkartan.se/#/non-existant too?

**Comment by rotsee** [comment]
>should there be something for fruktkartan.se/#/non-existant too?
Maybe, what do you think?

Aside from that, I'd like to at least add some basic styling to the 404 before closing this issue.

**Comment by quite** [comment]
Yes I think there could be something 404-like for unknown vue-routes.

I think avoid to create 404s, with redirects when needed, is more important than styling the 404 page :)
