### ISSUE TITLE
Harmonize tree types in frontend and API

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan#5]
List in src/components/Map.vue with the API's routes/v1/validTreeTypes.json

Or perhaps centralize somehow..

**Comment by rotsee** [comment]
Trees are now grouped into a 2-leveled hierarchy (`tree` < `tree-plum` < `Körsbärsplommon`) in the API, corresponding more or less to the current set of icons. Frontend just needs to map groups to icons.
