### ISSUE TITLE
Display lat lon coords somewhere

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan#50]
Should we? It could be useful when adding a tree. But as well along with other info when showing a tree...

**Comment by rotsee** [comment]
+1
Sounds very useful. I'm not sure if [`geo:X,Y` uri scheme](https://tools.ietf.org/html/rfc5870) is well supported enough in 2020 to be useful here (for opening a map application if available)

**Comment by quite** [comment]
At least on android, clicking such URI in a browser generates some intent, and asks which map app I want to open it in (with *just once* or *always* option)

**Comment by rotsee** [comment]
Added in https://github.com/fruktkartan/fruktkartan/commit/94ca196ad405e013fbeeb207dd3b2b3c07c83c7c
