### ISSUE TITLE
Empty icons for "svarta vinbär" (and red currants cluster doesn't look like that!)

### ISSUE THREAD

**Issue by theold190** [fruktkartan/fruktkartan#55]
"svarta vinbär" bushes seems to have an empty icon. You can find an example here: https://fruktkartan.se/#/t/1562700434.

It would be great to have a non-empty icon for the supported berries. Maybe "röda vinbär" can be used as a base for new icon?

**Comment by quite** [comment]
I agree. Except that, ouch, the red currants icon is really just the seabuckthorn coloured red. Currants doesn't look like that! :o

**Comment by quite** [comment]
@rotsee do you think the original author of the icons would come to the rescue? who is it? :)

**Comment by quite** [comment]
@theold190 btw, i think i remember there being red currants around that place as well, years ago ;-D

**Comment by theold190** [comment]
Yes, correct, there are red currants deeper in bostadsrättsförening area. Not sure if they should be added.

I can see that topic has changed and now includes few fixes. It might be nicer to have separate issue per detected problem. 
 Or should I report other "black currant" related problems in this issue also?

**Comment by rotsee** [comment]
ping @ungripped
What it you or Cecilia who did the current icons for Fruktkartan?

**Comment by ungripped** [comment]
The original icons were adapted for smaller displays by me from Cecilias illustrations. I don't think the current ones are from that though, I think there were only 5 or 6 icons. Are these perhaps from some stock photo library? 🤔

**Comment by rotsee** [comment]
Right, we also inherited some additional icons from Fruktsam, when we merged our database with theirs some years back. I can reach out to someone who was active in that project, and see if they remember who created those

**Comment by quite** [comment]
Oj, I found this on a simple search: http://pedromacloureiro.com/2014/12/fruktkartan-icons-design/

ungripped :wave: :)

**Comment by quite** [comment]
pedro will draw some currants :)

**Comment by theold190** [comment]
Nicely done! It looks beautiful.
