### ISSUE TITLE
"Svarta vinbär" option is not present in "Valj träd att visa" menu

### ISSUE THREAD

**Issue by theold190** [fruktkartan/fruktkartan#57]
It seems that fruktkartan allows to add "svarta vinbär" (ex. https://fruktkartan.se/#/t/1562700434) ...

 - [ ] but they are not available in "Valj träd att visa" menu.

 - [x] Also, black currant places are not displayed when "Alla bärställen" is selected in "Valj träd att visa" menu. I assume this is probably same or related to issue above.

Expected behavior: either have black currant in "Valj träd att visa" menu or show black currant places when "Alla bärställen" is selected.

**Comment by rotsee** [comment]
The frontend is currently out of sync with the API.
- Short term fix: Update relevant json files.
- Long term fix: Use the API as the only authority for available tree sorts

**Comment by quite** [comment]
Blackcurrants are now displayed among "Alla bärställen". Until blackcurrants gets its own icon in #55, they cannot be displayed alone.

**Comment by theold190** [comment]
I can confirm that blackcurrant are displayed when I select "Alla bärställen". Thanks! 

It is fine for me to create a separate issue for long-term solution and close this issue.

Not sure what routines are defined here. Should I or someone else close this issue?

**Comment by quite** [comment]
Ah routines... It's adhoc and quaintly chaotic around here. Let this one simmer for a while. I have some lf my mothers blackberry jam.

**Comment by theold190** [comment]
Great work! I can confirm that it works as expected already now.
