### ISSUE TITLE
Map tiles are not loaded on highest zoom level

### ISSUE THREAD

**Issue by rotsee** [fruktkartan/fruktkartan#8]

**Comment by quite** [comment]
Maybe something with that tileset not supporting that high zoom? I like the Hydda tiles from OSM.se, what do you think? This problems seems to be gone (maybe maxzoom did it). https://quite--fruktkartan.netlify.com/

**Comment by rotsee** [comment]
I like those! Much cleaner

**Comment by quite** [comment]
How is the max zoom for you?

**Comment by rotsee** [comment]
Max zoom looks good!

**Comment by quite** [comment]
Yay
